#!/bin/bash

# Update packages
sudo yum update -y

# Install Java 17 and wget
sudo yum install -y wget java-21-amazon-corretto-devel

# Create nexus user if it doesn't exist
id nexus >/dev/null 2>&1 || sudo useradd nexus

# Create application directory
sudo mkdir -p /app
cd /app

# Download Nexus
sudo wget -O nexus.tar.gz \
https://download.sonatype.com/nexus/3/nexus-3.89.1-02-linux-x86_64.tar.gz

# Extract Nexus
sudo tar -xzf nexus.tar.gz

# Rename installation directory
sudo mv nexus-3.89.1-02 nexus

# Set ownership
sudo chown -R nexus:nexus /app/nexus
sudo chown -R nexus:nexus /app/sonatype-work

# Configure Nexus to run as nexus user
echo 'run_as_user="nexus"' | sudo tee /app/nexus/bin/nexus.rc

# Reduce memory usage for 1GB RAM servers
sudo sed -i 's/^-Xms.*/-Xms512m/' /app/nexus/bin/nexus.vmoptions
sudo sed -i 's/^-Xmx.*/-Xmx512m/' /app/nexus/bin/nexus.vmoptions
sudo sed -i 's/^-XX:MaxDirectMemorySize=.*/-XX:MaxDirectMemorySize=512m/' /app/nexus/bin/nexus.vmoptions

# Create systemd service
sudo tee /etc/systemd/system/nexus.service > /dev/null <<EOF
[Unit]
Description=Nexus Repository Manager
After=network.target

[Service]
Type=forking
LimitNOFILE=65536
User=nexus
Group=nexus
ExecStart=/app/nexus/bin/nexus start
ExecStop=/app/nexus/bin/nexus stop
Restart=on-abort

[Install]
WantedBy=multi-user.target
EOF

# Reload systemd
sudo systemctl daemon-reload

# Enable and start Nexus
sudo systemctl enable nexus
sudo systemctl start nexus

# Check status
sudo systemctl status nexus --no-pager
